### PR TITLE
Introduce a TI TAS2557 Stereo driver for xiaomi-clover

### PR DESCRIPTION
**Pull request by setotau**
It' s very experimental TI TAS2557 driver for xiaomi-clover ported from https://github.com/pix106/android_kernel_xiaomi_southwest-4.19.
I've only got it compiled, but not tested on real device.

### CODE REVIEW

**Comment by M0Rf30** [comment]
Hi @kubentd
I need to test it both on sdm660 and msm8953

In the past I've done this
https://github.com/msm8953-mainline/linux/pull/47

device seemed to be detected and I tried to mod based on tas2559 sources taken from sdm845-mainline repo

**Comment by setotau** [comment]
I've seen differences between stereo and mono driver, so i' ve decided to port this variant.
P. S.: Sorry for my bad english

**Comment by minlexx** [comment]
-next-stable branch is often force pushed, so to  make commit history in PR look sane, send PR targeting one of stable branches (like 6.3.y one) (or rebase on today's sdm660-next-stable)

maybe even wait for 6.4.y one, should be ready soon

**Comment by minlexx** [comment]
Which kernel version this depends on? 6.3? 6.4?

**Comment by minlexx** [comment]
This is just a speaker amplifier driver, right? It does not allow to play any audio right now, because SoC audio codec driver support is needed first?

**Comment by setotau** [comment]
It depends on 6.4.

**Comment by rvc11twil** [comment]
might as well use it with xiaomi whyred

**Pull request closed without merging**
